spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:sqlite:./group_management.db}
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
server.port=${PORT:8082}
server.servlet.session.tracking-modes=cookie
spring.thymeleaf.cache=false
